# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=20)),
                ('apwd', models.CharField(max_length=50)),
                ('aphone', models.PositiveIntegerField()),
                ('aemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'T_administrator',
            },
        ),
        migrations.CreateModel(
            name='BookBorrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('bname', models.CharField(max_length=30)),
                ('bnumber', models.PositiveIntegerField()),
                ('borrow', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'T_bookborrowing',
            },
        ),
        migrations.CreateModel(
            name='BookClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('clocation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'T_bookclass',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('inum', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('iname', models.CharField(max_length=30)),
                ('iauthor', models.CharField(max_length=20)),
                ('ipublish', models.CharField(max_length=30)),
                ('intro', models.TextField()),
                ('itype', models.CharField(max_length=20)),
                ('iprice', models.DecimalField(decimal_places=2, max_digits=3)),
                ('iamount', models.PositiveIntegerField()),
                ('bookclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.BookClass')),
            ],
            options={
                'db_table': 'T_information',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('uaccount', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=50)),
                ('uphone', models.PositiveIntegerField()),
                ('uemail', models.EmailField(max_length=254)),
                ('unum', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'T_user',
            },
        ),
        migrations.AddField(
            model_name='bookborrowing',
            name='binfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Information'),
        ),
        migrations.AddField(
            model_name='bookborrowing',
            name='buser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.User'),
        ),
    ]
